import { getYears } from "../../utils";

export const skills = [
  {
    name: "Figma",
    color: "#E8E4DC",
    accentColor: "#56514d",
    textColor: "#2B2520",
    borderColor: "#D4CFC7",
    desc: "Design and Prototyping tool",
    icon: "figma",
    experience: 3,
    use: "Moodboards, Design, Prototyping",
    years: getYears(2023),
    type: "Design Tool",
    cardIndex: 0,
  },
  {
    name: "AWS",
    color: "#E8E0D5",
    textColor: "#2B2520",
    borderColor: "#C8BFB4",
    accentColor: "#FF9900",
    desc: "Cloud computing platform for building scalable, highly available serverless infrastructure",
    icon: "aws",
    experience: 4,
    use: "Serverless Lambdas, APIs, DynamoDB, s3, SES",
    years: getYears(2021),
    type: "Cloud Computing",
    cardIndex: 1,
  },
  {
    name: "Databases",
    color: "#DCD4C8",
    textColor: "#2B2520",
    borderColor: "#BCB4A8",
    desc: "SQL and NoSQL database systems for structured and flexible data management",
    icon: "database",
    experience: 4,
    use: "SQL, MySQL, Graph, PL/SQL, DynamoDB, MongoDB",
    years: getYears(2017),
    type: "Data Storage",
    cardIndex: 2,
  },
  {
    name: ".NET",
    color: "#C9BDB0",
    textColor: "#1F1B18",
    borderColor: "#A99D90",
    desc: "Microsoft framework for building cross-platform applications and web services",
    icon: "dotnet",
    experience: 3,
    use: "C#, ASP.NET, Web APIs, Backend Services",
    years: getYears(2018),
    type: "Framework",
    cardIndex: 3,
  },
  {
    name: "Full-Stack JavaScript",
    color: "#A89B8E",
    textColor: "#1F1B18",
    borderColor: "#887B6E",
    desc: "My primary language for full-stack development",
    icon: "js",
    experience: 5,
    use: "Frontend, Backend (Node.js), APIs, TypeScript",
    years: getYears(2018),
    type: "Programming Language",
    cardIndex: 4,
  },
  {
    name: "React",
    color: "#C4B5A0",
    textColor: "#1F1B18",
    borderColor: "#A49580",
    desc: "UI JavaScript library specializing in building reusable components for simple to complex interfaces",
    experience: 5,
    use: "UI, Web Development, Mobile app development",
    years: getYears(2019),
    type: "Library",
    icon: "react",
    cardIndex: 5,
  },
];
