export const skills = [
    {
    name: "Figma",
    color: "#A259FF",
    desc: "Design and prototyping tool",
    icon: "✦",
    experience: 5,
    use: "Software",
    years: 6,
  },
  {
    name: "Sketch",
    color: "#FDB300",
    desc: "Vector graphics editor",
    icon: "◆",
    experience: 5,
    use: "Software",
    years: 6,
  },
  {
    name: "Adobe XD",
    color: "#FF61F6",
    desc: "UX/UI design platform",
    icon: "▲",
    experience: 5,
    use: "Software",
    years: 6,
  },
  {
    name: "Principle",
    color: "#5A67D8",
    desc: "Animation & interaction design",
    icon: "●",
    experience: 5,
    use: "Software",
    years: 6,
  },
]